---
# file: windows_playbooks.yml 适用windows系统
- hosts: windows
  vars:
    - linux_path: /root/update
    - windows_path: C:\hlTest\hl_bizdemo\files\update
  tasks:
    - name: test connection
      win_ping:
      tags:
      - always
      
    - name: del directory path\incremental\
      win_file: dest={{windows_path}}\\incremental\ state=directory state=absent
      tags:
      - zengliang

    - name: del file path\hl_bizdemo.jar
      win_file: dest={{windows_path}}\\hl_bizdemo.jar state=absent
      tags:
      - quanliang

    - name: bak file hl_bizdemo.jar
      raw: copy {{windows_path}}\..\..\lib\hl_bizdemo.jar {{windows_path}}\..\bak\hl_bizdemo_{{ansible_date_time['iso8601_basic_short']}}.jar
      ignore_errors: True
      tags:
      - always

    - name: copy directory incremental
      win_copy: src={{linux_path}}/incremental dest={{windows_path}}
      ignore_errors: True
      tags:
      - zengliang

    - name: copy file hl_bizdemo.jar
      win_copy: src={{linux_path}}/hl_bizdemo.jar dest={{windows_path}}\\hl_bizdemo.jar
      ignore_errors: True
      tags:
      - quanliang

    - name: exec bat
      raw: C:\hlTest\hl_bizdemo\bin\updateServer.bat
      tags:
      - always